version: "3.4"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    image: dev-rails-api
    container_name: rails-api
    tty: true
    env_file:
      - .env
    working_dir: /workspace/
    volumes:
      - type: bind
        source: $PWD
        target: /workspace/rails-api
    ports:
      - 3000:3000

networks:
  shared-network:
    external: true
